/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainController: typeof import('./src/components/MainController.vue')['default']
    StartScreen: typeof import('./src/components/StartScreen.vue')['default']
    WelcomeScreen: typeof import('./src/components/WelcomeScreen.vue')['default']
  }
}
